name: 'Delete old artifacts'
on:
  workflow_dispatch:
    inputs:
      message:
        description: 'Triggered for Delete old artifacts'
        required: false
        default: 'Delete old artifacts'
      releaseTags:
        description: 'tag to update'
        required: true
      snapshotTags:
        description: 'tag to be replaced'
        required: true
      base:
        description: 'base branch for PR'
        required: true

jobs:
  delete-artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: kolpav/purge-artifacts-action@v1
        with:
          token: ${{ secrets. access_token }}
          expire-in: 2days # Setting this to 0 will delete all artifacts